apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dsileecher-dce6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dsileecher-dce6"
  template:
    metadata:
      labels:
        app: "dsileecher-dce6"
    spec:
      containers:
        - name: "dsileecher-dce6"
          image: "tortoolkit.azurecr.io/dsileecher"
          ports:
          - containerPort: 80