apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dsileecher-3d93"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dsileecher-3d93"
  template:
    metadata:
      labels:
        app: "dsileecher-3d93"
    spec:
      containers:
        - name: "dsileecher-3d93"
          image: "dsfedggrdh.azurecr.io/dsileecher"
          ports:
          - containerPort: 80