apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dsileecher-eb0d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dsileecher-eb0d"
  template:
    metadata:
      labels:
        app: "dsileecher-eb0d"
    spec:
      containers:
        - name: "dsileecher-eb0d"
          image: "drghrshyn.azurecr.io/dsileecher"
          ports:
          - containerPort: 80